"""archive core

Revision ID: 0001
Revises:
Create Date: 2026-07-13 23:51:11.576009

Creates the 11 core archive tables. Datetime columns are declared here as
sa.String(): at the ORM layer they are introspect.db.UTCDateTime (a TypeDecorator
over String storing ISO-8601 UTC text), whose DDL is an ordinary text column. Using
sa.String() keeps this migration self-contained and decoupled from app code.
Note: favorites / FTS tables are intentionally deferred to a later phase.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('files_seen', sa.Integer(), nullable=False),
    sa.Column('records_added', sa.Integer(), nullable=False),
    sa.Column('records_skipped_duplicate', sa.Integer(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dir_slug', sa.String(), nullable=False),
    sa.Column('resolved_cwd', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dir_slug')
    )
    op.create_table('sessions',
    sa.Column('session_uuid', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('last_activity_at', sa.String(), nullable=True),
    sa.Column('ai_title', sa.String(), nullable=True),
    sa.Column('custom_title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('session_uuid')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('agent_hex_id', sa.String(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=True),
    sa.Column('agent_description', sa.String(), nullable=True),
    sa.Column('parent_tool_use_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'kind', 'agent_hex_id', name='uq_transcript_identity')
    )
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('byte_offset_checkpoint', sa.Integer(), nullable=False),
    sa.Column('last_size', sa.Integer(), nullable=False),
    sa.Column('prefix_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.String(), nullable=False),
    sa.Column('gone_detected_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', 'generation', name='uq_source_files_path_generation')
    )
    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('byte_offset', sa.Integer(), nullable=False),
    sa.Column('raw_line', sa.LargeBinary(), nullable=False),
    sa.Column('line_sha256', sa.String(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=True),
    sa.Column('record_uuid', sa.String(), nullable=True),
    sa.Column('detected_cli_version', sa.String(), nullable=True),
    sa.Column('parsed_with_schema_version', sa.String(), nullable=True),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'line_number', name='uq_raw_records_file_line')
    )
    op.create_index('ix_raw_records_transcript_sha', 'raw_records', ['transcript_id', 'line_sha256'], unique=False)
    op.create_index('ix_raw_records_transcript_uuid', 'raw_records', ['transcript_id', 'record_uuid'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_record_id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('record_uuid', sa.String(), nullable=False),
    sa.Column('parent_uuid', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('cwd', sa.String(), nullable=True),
    sa.Column('git_branch', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_record_id')
    )
    op.create_table('parse_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_record_id', sa.Integer(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_record_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_kind', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_record_id')
    )
    op.create_table('content_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('block_kind', sa.String(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_use_id', sa.String(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_creation_input_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_usage')
    op.drop_table('content_blocks')
    op.drop_table('session_events')
    op.drop_table('parse_anomalies')
    op.drop_table('messages')
    op.drop_index('ix_raw_records_transcript_uuid', table_name='raw_records')
    op.drop_index('ix_raw_records_transcript_sha', table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_table('source_files')
    op.drop_table('transcripts')
    op.drop_table('sessions')
    op.drop_table('projects')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
